apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: devzone
build:
  artifacts:
    - image: sivaprasadreddy/devzone
      context: ./application
      jib: {}
      #buildpacks:
      #  builder: paketobuildpacks/builder:base

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
