apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: devzone
build:
  artifacts:
    - image: sivaprasadreddy/devzone
      context: .
      jib:
        project: application
      #buildpacks:
      #  builder: paketobuildpacks/builder:base

deploy:
  kubectl:
    manifests:
      - deployment/k8s/*.yaml
